public with sharing class CaseUtils {
    public static final String STATUS_IN_PROGRES = 'In Progress';
    public static final String STATUS_TO_DO = 'To Do';
    public static final String STATUS_DONE_SUCCESS = 'Done - success';
    public static final String STATUS_DONE_FAILURE = 'Done - failure';

    public static final String PRIORITY_HIGH = 'High';
    public static final String PRIORITY_MEDIUM = 'Medium';
    public static final String PRIORITY_LOW = 'Low';
}
